[character]
symbol = "♍"
error_symbol = "♓"
use_symbol_for_status = true

[git_state]
progress_divider = " of "
cherry_pick = "🍒 Picking"

[git_status]
prefix = ""
suffix = " "
conflicted = "🚩"
ahead = "🔺"
behind = "🔻"
diverged = "💠"
untracked = "🔍"
stashed = "💼"
modified = "✏"
renamed = "🔨"
deleted = "💀"
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"

[golang]
symbol = "Go "

[hg_branch]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[haskell]
disabled = true

[php]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[conda]
disabled = true

[memory_usage]
disabled = true

[aws]
disabled = true

[env_var]
disabled = true

[crystal]
disabled = true

[battery]
disabled = true

[time]
disabled = true
