prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    "package",
    "golang",
    "java",
    "nodejs",
    "python",
    "nix_shell",
    "memory_usage",
    "env_var",
    "cmd_duration",
    "line_break",
    "jobs",
    "time",
    "character",
]
