[character]
success_symbol = "♍"
error_symbol = "♓"

[git_state]
cherry_pick = "🍒 Picking"

[git_status]
conflicted = "🚩"
ahead = "🔺"
behind = "🔻"
diverged = "💠 "
untracked = "🔍 "
stashed = "💼 "
modified = "✏ "
renamed = "🔨"
deleted = "💀"
staged = "++"

[golang]
symbol = "Go "

[hg_branch]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[php]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[conda]
disabled = true

[memory_usage]
disabled = true

[aws]
disabled = true

[env_var]
disabled = true

[crystal]
disabled = true

[battery]
disabled = true

[time]
disabled = true
